"""Add DocumentoVersion

Revision ID: 25e4710d9897
Revises: 6826d3c888e5
Create Date: 2026-08-12 19:56:20.476598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e4710d9897'
down_revision: Union[str, None] = '6826d3c888e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_versiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('path_archivo', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_libreria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_versiones_documento_id'), 'documento_versiones', ['documento_id'], unique=False)
    op.create_index(op.f('ix_documento_versiones_id'), 'documento_versiones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documento_versiones_id'), table_name='documento_versiones')
    op.drop_index(op.f('ix_documento_versiones_documento_id'), table_name='documento_versiones')
    op.drop_table('documento_versiones')
    # ### end Alembic commands ###
