"""add_jurisdiccion

Revision ID: f2d8ab2ff2e7
Revises: 25e4710d9897
Create Date: 2026-08-12 20:35:26.294533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d8ab2ff2e7'
down_revision: Union[str, None] = '25e4710d9897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('jurisdiccion', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'jurisdiccion')
    # ### end Alembic commands ###
